apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hy3sbfu62-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hy3sbfu62-python 
  name: hy3sbfu62-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hy3sbfu62-python 
